/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PencilPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/view.ts
var import_obsidian3 = require("obsidian");

// src/types.ts
var EMPTY_DATA = {
  version: 1,
  strokes: []
};
function parseData(text) {
  const trimmed = text.trim();
  if (!trimmed)
    return { ...EMPTY_DATA };
  try {
    const data = JSON.parse(trimmed);
    if (!data || typeof data !== "object")
      return { ...EMPTY_DATA };
    if (!Array.isArray(data.strokes))
      data.strokes = [];
    data.version = 1;
    return data;
  } catch (e) {
    return { ...EMPTY_DATA };
  }
}
function serializeData(data) {
  return JSON.stringify(data, null, 2);
}

// src/icons.ts
var import_obsidian = require("obsidian");
var LUCIDE_24 = {
  "pencil-pencil": `
		<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />
		<path d="m15 5 4 4" />
	`,
  "pencil-eraser": `
		<path d="M21 21H8a2 2 0 0 1-1.42-.587l-3.994-3.999a2 2 0 0 1 0-2.828l10-10a2 2 0 0 1 2.829 0l5.999 6a2 2 0 0 1 0 2.828L12.834 21" />
		<path d="m5.082 11.09 8.828 8.828" />
	`,
  "pencil-select": `
		<path d="M7 22a5 5 0 0 1-2-4" />
		<path d="M7 16.93c.96.43 1.96.74 2.99.91" />
		<path d="M3.34 14A6.8 6.8 0 0 1 2 10c0-4.42 4.48-8 10-8s10 3.58 10 8a7.19 7.19 0 0 1-.33 2" />
		<path d="M5 18a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" />
		<path d="M14.33 22h-.09a.35.35 0 0 1-.24-.32v-10a.34.34 0 0 1 .33-.34c.08 0 .15.03.21.08l7.34 6a.33.33 0 0 1-.21.59h-4.49l-2.57 3.85a.35.35 0 0 1-.28.14z" />
	`,
  "pencil-hand": `
		<path d="M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2" />
		<path d="M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2" />
		<path d="M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8" />
		<path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
	`,
  "pencil-undo": `
		<path d="M9 14 L 4 9 l 5-5" />
		<path d="M4 9 h 10.5 a 5.5 5.5 0 0 1 5.5 5.5 a 5.5 5.5 0 0 1-5.5 5.5 H 11" />
	`,
  "pencil-redo": `
		<path d="m15 14 5-5-5-5" />
		<path d="M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13" />
	`,
  "pencil-zoom-in": `
		<circle cx="11" cy="11" r="8" />
		<line x1="21" x2="16.65" y1="21" y2="16.65" />
		<line x1="11" x2="11" y1="8" y2="14" />
		<line x1="8" x2="14" y1="11" y2="11" />
	`,
  "pencil-zoom-out": `
		<circle cx="11" cy="11" r="8" />
		<line x1="21" x2="16.65" y1="21" y2="16.65" />
		<line x1="8" x2="14" y1="11" y2="11" />
	`,
  "pencil-fit": `
		<path d="M15 3h6v6" />
		<path d="m21 3-7 7" />
		<path d="m3 21 7-7" />
		<path d="M9 21H3v-6" />
	`,
  "pencil-reset": `
		<line x1="2" x2="5" y1="12" y2="12" />
		<line x1="19" x2="22" y1="12" y2="12" />
		<line x1="12" x2="12" y1="2" y2="5" />
		<line x1="12" x2="12" y1="19" y2="22" />
		<circle cx="12" cy="12" r="7" />
		<circle cx="12" cy="12" r="3" />
	`,
  "pencil-trash": `
		<path d="M10 11v6" />
		<path d="M14 11v6" />
		<path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
		<path d="M3 6h18" />
		<path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
	`,
  "pencil-clear": `
		<circle cx="12" cy="12" r="10" />
		<path d="m15 9-6 6" />
		<path d="m9 9 6 6" />
	`,
  // Two strokes of differing weight: a glyph for pressure thickness variation.
  "pencil-pressure": `
		<line x1="4" y1="8" x2="20" y2="8" stroke-width="1" />
		<line x1="4" y1="13" x2="20" y2="13" stroke-width="2.5" />
		<line x1="4" y1="18" x2="20" y2="18" stroke-width="4.5" />
	`
};
var registered = false;
function registerIcons() {
  if (registered)
    return;
  registered = true;
  for (const [name, inner] of Object.entries(LUCIDE_24)) {
    const svg = `<g transform="scale(4.166667)" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</g>`;
    (0, import_obsidian.addIcon)(name, svg);
  }
}
var ICON = {
  pencil: "pencil-pencil",
  eraser: "pencil-eraser",
  select: "pencil-select",
  hand: "pencil-hand",
  undo: "pencil-undo",
  redo: "pencil-redo",
  zoomIn: "pencil-zoom-in",
  zoomOut: "pencil-zoom-out",
  fit: "pencil-fit",
  reset: "pencil-reset",
  trash: "pencil-trash",
  clear: "pencil-clear",
  pressure: "pencil-pressure"
};

// src/confirm.ts
var import_obsidian2 = require("obsidian");
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, message, onConfirm, confirmText = "Confirm", cancelText = "Cancel") {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
    this.confirmText = confirmText;
    this.cancelText = cancelText;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    new import_obsidian2.Setting(contentEl).addButton(
      (b) => b.setButtonText(this.cancelText).onClick(() => this.close())
    ).addButton(
      (b) => b.setButtonText(this.confirmText).setCta().onClick(() => {
        this.onConfirm();
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/view.ts
var VIEW_TYPE_PENCIL = "pencil-whiteboard";
var BUILTIN_COLORS = [
  "#ffffff",
  "#f1f1f1",
  "#ffd166",
  "#ef476f",
  "#06d6a0",
  "#118ab2",
  "#c77dff",
  "#222222"
];
var SIZES = [1.5, 3, 6, 12];
var MIN_SCALE = 0.05;
var MAX_SCALE = 20;
function uid() {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
}
function strokeBounds(stroke) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  const pad = stroke.size;
  for (const p of stroke.points) {
    if (p.x < minX)
      minX = p.x;
    if (p.y < minY)
      minY = p.y;
    if (p.x > maxX)
      maxX = p.x;
    if (p.y > maxY)
      maxY = p.y;
  }
  return { minX: minX - pad, minY: minY - pad, maxX: maxX + pad, maxY: maxY + pad };
}
function distToSegment(px, py, ax, ay, bx, by) {
  const dx = bx - ax;
  const dy = by - ay;
  const len2 = dx * dx + dy * dy;
  let t = len2 === 0 ? 0 : ((px - ax) * dx + (py - ay) * dy) / len2;
  if (t < 0)
    t = 0;
  else if (t > 1)
    t = 1;
  const cx = ax + t * dx;
  const cy = ay + t * dy;
  const ex = px - cx;
  const ey = py - cy;
  return Math.sqrt(ex * ex + ey * ey);
}
function strokeHit(stroke, x, y, radius) {
  const r = radius + stroke.size;
  const b = strokeBounds(stroke);
  if (x < b.minX - r || x > b.maxX + r || y < b.minY - r || y > b.maxY + r)
    return false;
  const pts = stroke.points;
  if (pts.length === 1) {
    const dx = pts[0].x - x;
    const dy = pts[0].y - y;
    return dx * dx + dy * dy <= r * r;
  }
  for (let i = 1; i < pts.length; i++) {
    if (distToSegment(x, y, pts[i - 1].x, pts[i - 1].y, pts[i].x, pts[i].y) <= r)
      return true;
  }
  return false;
}
function rectIntersectsBounds(r, b) {
  return !(r.maxX < b.minX || r.minX > b.maxX || r.maxY < b.minY || r.minY > b.maxY);
}
var PencilWhiteboardView = class extends import_obsidian3.TextFileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.boardData = { ...EMPTY_DATA };
    this.view = { x: 0, y: 0, scale: 1 };
    this.tool = "pencil";
    this.color = BUILTIN_COLORS[0];
    this.size = SIZES[1];
    this.eraseRadius = 8;
    this.pointers = /* @__PURE__ */ new Map();
    this.penActive = false;
    /** Once a pen has been used in this view, finger touches default to pan
     * (Apple Pencil convention). Until then, single-finger touches draw. */
    this.penSeen = false;
    this.pressureBtn = null;
    this.pinch = null;
    this.panStart = null;
    this.selectionBox = null;
    this.selectedIds = /* @__PURE__ */ new Set();
    this.selectionDrag = null;
    this.undoStack = [];
    this.redoStack = [];
    this.resizeObserver = null;
    this.renderRequested = false;
    this.dpr = 1;
    this.onWindowKeyDown = () => {
    };
    /** Active-state check functions for toolbar buttons/swatches, keyed by element. */
    this.activeChecks = /* @__PURE__ */ new WeakMap();
    this.plugin = plugin;
  }
  allColors() {
    return [...BUILTIN_COLORS, ...this.plugin.settings.customColors];
  }
  getViewType() {
    return VIEW_TYPE_PENCIL;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "Whiteboard";
  }
  getIcon() {
    return ICON.pencil;
  }
  getViewData() {
    return serializeData(this.boardData);
  }
  setViewData(data, _clear) {
    this.boardData = parseData(data);
    this.undoStack = [];
    this.redoStack = [];
    this.selectedIds.clear();
    if (this.boardData.view) {
      this.view = { ...this.boardData.view };
    } else {
      this.view = { x: 0, y: 0, scale: 1 };
    }
    this.scheduleRender();
  }
  clear() {
    this.boardData = { ...EMPTY_DATA };
    this.undoStack = [];
    this.redoStack = [];
    this.selectedIds.clear();
    this.scheduleRender();
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("pencil-root");
    this.toolbar = root.createDiv({ cls: "pencil-toolbar" });
    this.container = root.createDiv({ cls: "pencil-canvas-wrap" });
    this.canvas = this.container.createEl("canvas", { cls: "pencil-canvas" });
    this.overlay = this.container.createEl("canvas", { cls: "pencil-canvas pencil-overlay" });
    this.statusEl = root.createDiv({ cls: "pencil-status" });
    this.buildToolbar();
    this.attachPointerHandlers();
    this.onWindowKeyDown = (e) => this.handleKey(e);
    window.addEventListener("keydown", this.onWindowKeyDown);
    this.resizeObserver = new ResizeObserver(() => this.resize());
    this.resizeObserver.observe(this.container);
    this.resize();
  }
  async onClose() {
    window.removeEventListener("keydown", this.onWindowKeyDown);
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }
    this.contentEl.empty();
  }
  buildToolbar() {
    const tb = this.toolbar;
    tb.empty();
    const makeBtn = (label, shortLabel, icon, onClick, isActive) => {
      const btn = tb.createEl("button", {
        cls: "pencil-btn",
        attr: { "aria-label": label, title: label }
      });
      (0, import_obsidian3.setIcon)(btn, icon);
      const svg = btn.querySelector("svg");
      if (svg) {
        svg.setAttribute("width", "18");
        svg.setAttribute("height", "18");
      }
      const rendered = svg && svg.innerHTML.trim().length > 0;
      if (!rendered) {
        btn.empty();
        btn.addClass("pencil-btn-text");
        btn.setText(shortLabel);
      }
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        onClick();
        this.refreshToolbarState();
      });
      if (isActive)
        this.activeChecks.set(btn, isActive);
      return btn;
    };
    makeBtn("Pencil", "Pen", ICON.pencil, () => this.tool = "pencil", () => this.tool === "pencil");
    makeBtn("Eraser", "Erase", ICON.eraser, () => this.tool = "eraser", () => this.tool === "eraser");
    makeBtn("Select", "Select", ICON.select, () => this.tool = "select", () => this.tool === "select");
    makeBtn("Pan", "Pan", ICON.hand, () => this.tool = "pan", () => this.tool === "pan");
    tb.createDiv({ cls: "pencil-sep" });
    const builtinCount = BUILTIN_COLORS.length;
    const palette = this.allColors();
    for (let i = 0; i < palette.length; i++) {
      const c = palette[i];
      const isCustom = i >= builtinCount;
      const sw = tb.createDiv({
        cls: isCustom ? "pencil-swatch pencil-swatch-custom" : "pencil-swatch",
        attr: {
          "aria-label": `Color ${c}`,
          title: isCustom ? `${c} (long-press to remove)` : c
        }
      });
      sw.style.backgroundColor = c;
      sw.addEventListener("click", (e) => {
        e.preventDefault();
        this.color = c;
        this.refreshToolbarState();
      });
      if (isCustom)
        this.attachLongPressRemove(sw, c);
      this.activeChecks.set(sw, () => this.color === c);
    }
    const addBtn = tb.createDiv({
      cls: "pencil-swatch pencil-swatch-add",
      attr: { "aria-label": "Add color", title: "Add custom color" }
    });
    addBtn.setText("+");
    const colorInput = addBtn.createEl("input", { type: "color" });
    colorInput.addClass("pencil-color-input");
    colorInput.value = this.color || "#5b9dff";
    colorInput.addEventListener("change", () => {
      const value = colorInput.value;
      if (value)
        void this.addCustomColor(value);
    });
    tb.createDiv({ cls: "pencil-sep" });
    for (const s of SIZES) {
      const sw = tb.createDiv({ cls: "pencil-size", attr: { "aria-label": `Size ${s}`, title: `Size ${s}` } });
      const dot = sw.createDiv({ cls: "pencil-size-dot" });
      const px = Math.max(2, Math.min(20, s * 2));
      dot.style.width = `${px}px`;
      dot.style.height = `${px}px`;
      sw.addEventListener("click", (e) => {
        e.preventDefault();
        this.size = s;
        this.refreshToolbarState();
      });
      this.activeChecks.set(sw, () => this.size === s);
    }
    this.pressureBtn = makeBtn(
      "Pressure (pen thickness)",
      "Pressure",
      ICON.pressure,
      () => this.togglePressure(),
      () => this.plugin.settings.pressureEnabled
    );
    tb.createDiv({ cls: "pencil-sep" });
    makeBtn("Undo", "Undo", ICON.undo, () => this.undo());
    makeBtn("Redo", "Redo", ICON.redo, () => this.redo());
    tb.createDiv({ cls: "pencil-sep" });
    makeBtn("Zoom in", "+", ICON.zoomIn, () => this.zoomAtCenter(1.2));
    makeBtn("Zoom out", "\u2212", ICON.zoomOut, () => this.zoomAtCenter(1 / 1.2));
    makeBtn("Fit", "Fit", ICON.fit, () => this.zoomToFit());
    makeBtn("Reset view", "Reset", ICON.reset, () => this.resetView());
    tb.createDiv({ cls: "pencil-sep" });
    makeBtn("Delete selection", "Del", ICON.trash, () => this.deleteSelection());
    makeBtn("Clear all", "Clear", ICON.clear, () => this.clearAllPrompt());
    this.refreshToolbarState();
  }
  async addCustomColor(hex) {
    const normalized = hex.toLowerCase();
    const all = this.allColors().map((c) => c.toLowerCase());
    if (!all.includes(normalized)) {
      this.plugin.settings.customColors.push(normalized);
      await this.plugin.saveSettings();
    }
    this.color = normalized;
    window.setTimeout(() => this.buildToolbar(), 0);
  }
  async removeCustomColor(hex) {
    const normalized = hex.toLowerCase();
    const list = this.plugin.settings.customColors;
    const idx = list.findIndex((c) => c.toLowerCase() === normalized);
    if (idx === -1)
      return;
    list.splice(idx, 1);
    await this.plugin.saveSettings();
    if (this.color.toLowerCase() === normalized)
      this.color = BUILTIN_COLORS[0];
    window.setTimeout(() => this.buildToolbar(), 0);
  }
  attachLongPressRemove(el, hex) {
    let timer = null;
    let fired = false;
    const clear = () => {
      if (timer !== null) {
        window.clearTimeout(timer);
        timer = null;
      }
    };
    el.addEventListener("pointerdown", (e) => {
      if (e.button !== void 0 && e.button !== 0)
        return;
      fired = false;
      clear();
      timer = window.setTimeout(() => {
        fired = true;
        timer = null;
        new ConfirmModal(
          this.app,
          `Remove color ${hex} from the palette?`,
          () => void this.removeCustomColor(hex),
          "Remove"
        ).open();
      }, 600);
    });
    el.addEventListener("pointerup", clear);
    el.addEventListener("pointerleave", clear);
    el.addEventListener("pointercancel", clear);
    el.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      new ConfirmModal(
        this.app,
        `Remove color ${hex} from the palette?`,
        () => void this.removeCustomColor(hex),
        "Remove"
      ).open();
    });
    el.addEventListener(
      "click",
      (e) => {
        if (fired) {
          e.preventDefault();
          e.stopImmediatePropagation();
          fired = false;
        }
      },
      true
    );
  }
  togglePressure() {
    this.plugin.settings.pressureEnabled = !this.plugin.settings.pressureEnabled;
    void this.plugin.saveSettings();
    this.refreshToolbarState();
  }
  refreshToolbarState() {
    const els = this.toolbar.querySelectorAll("button, .pencil-swatch, .pencil-size");
    els.forEach((el) => {
      const check = this.activeChecks.get(el);
      if (check)
        el.toggleClass("is-active", check());
    });
    if (this.pressureBtn) {
      this.pressureBtn.setAttr(
        "title",
        this.plugin.settings.pressureEnabled ? "Pressure thickness: on for pen input (tap to turn off)" : "Pressure thickness: off (tap to turn on for pen input)"
      );
    }
  }
  resize() {
    const rect = this.container.getBoundingClientRect();
    this.dpr = window.devicePixelRatio || 1;
    for (const c of [this.canvas, this.overlay]) {
      c.width = Math.max(1, Math.floor(rect.width * this.dpr));
      c.height = Math.max(1, Math.floor(rect.height * this.dpr));
      c.style.width = `${rect.width}px`;
      c.style.height = `${rect.height}px`;
    }
    this.scheduleRender();
  }
  scheduleRender() {
    if (this.renderRequested)
      return;
    this.renderRequested = true;
    window.requestAnimationFrame(() => {
      this.renderRequested = false;
      this.render();
    });
  }
  screenToWorld(clientX, clientY) {
    const rect = this.container.getBoundingClientRect();
    const sx = clientX - rect.left;
    const sy = clientY - rect.top;
    return {
      x: (sx - this.view.x) / this.view.scale,
      y: (sy - this.view.y) / this.view.scale
    };
  }
  render() {
    const ctx = this.canvas.getContext("2d");
    if (!ctx)
      return;
    ctx.save();
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.fillStyle = "#1a1a1a";
    ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
    ctx.translate(this.view.x, this.view.y);
    ctx.scale(this.view.scale, this.view.scale);
    for (const stroke of this.boardData.strokes) {
      this.drawStroke(ctx, stroke, this.selectedIds.has(stroke.id));
    }
    ctx.restore();
    this.renderOverlay();
    this.updateStatus();
  }
  drawStroke(ctx, stroke, selected) {
    var _a, _b, _c;
    const pts = stroke.points;
    if (pts.length === 0)
      return;
    ctx.strokeStyle = stroke.color;
    ctx.fillStyle = stroke.color;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    if (pts.length === 1) {
      const p = pts[0];
      const r = Math.max(0.5, stroke.size * ((_a = p.p) != null ? _a : 0.5));
      ctx.beginPath();
      ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
      ctx.fill();
    } else {
      for (let i = 1; i < pts.length; i++) {
        const a = pts[i - 1];
        const b = pts[i];
        const pa = (_b = a.p) != null ? _b : 0.5;
        const pb = (_c = b.p) != null ? _c : 0.5;
        ctx.lineWidth = Math.max(0.5, stroke.size * (pa + pb));
        ctx.beginPath();
        ctx.moveTo(a.x, a.y);
        ctx.lineTo(b.x, b.y);
        ctx.stroke();
      }
    }
    if (selected) {
      const b = strokeBounds(stroke);
      ctx.save();
      ctx.lineWidth = 1 / this.view.scale;
      ctx.strokeStyle = "#5b9dff";
      ctx.setLineDash([4 / this.view.scale, 4 / this.view.scale]);
      ctx.strokeRect(b.minX, b.minY, b.maxX - b.minX, b.maxY - b.minY);
      ctx.restore();
    }
  }
  renderOverlay() {
    const ctx = this.overlay.getContext("2d");
    if (!ctx)
      return;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, this.overlay.width, this.overlay.height);
    ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
    if (this.selectionBox) {
      const { x0, y0, x1, y1 } = this.selectionBox;
      const sx0 = x0 * this.view.scale + this.view.x;
      const sy0 = y0 * this.view.scale + this.view.y;
      const sx1 = x1 * this.view.scale + this.view.x;
      const sy1 = y1 * this.view.scale + this.view.y;
      const x = Math.min(sx0, sx1);
      const y = Math.min(sy0, sy1);
      const w = Math.abs(sx1 - sx0);
      const h = Math.abs(sy1 - sy0);
      ctx.save();
      ctx.fillStyle = "rgba(91,157,255,0.12)";
      ctx.strokeStyle = "rgba(91,157,255,0.8)";
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 4]);
      ctx.fillRect(x, y, w, h);
      ctx.strokeRect(x, y, w, h);
      ctx.restore();
    }
  }
  updateStatus() {
    const zoom = Math.round(this.view.scale * 100);
    const sel = this.selectedIds.size;
    const parts = [`${this.boardData.strokes.length} strokes`, `${zoom}%`];
    if (sel > 0)
      parts.push(`${sel} selected`);
    this.statusEl.setText(parts.join("  \xB7  "));
  }
  attachPointerHandlers() {
    const el = this.container;
    el.addEventListener("pointerdown", (e) => this.onPointerDown(e));
    el.addEventListener("pointermove", (e) => this.onPointerMove(e));
    el.addEventListener("pointerup", (e) => this.onPointerUp(e));
    el.addEventListener("pointercancel", (e) => this.onPointerUp(e));
    el.addEventListener("pointerleave", (e) => this.onPointerUp(e));
    el.addEventListener("wheel", (e) => this.onWheel(e), { passive: false });
    el.addEventListener("contextmenu", (e) => e.preventDefault());
  }
  isPenLikeForDrawing(e) {
    if (e.pointerType === "pen")
      return true;
    if (e.pointerType === "mouse" && e.button === 0)
      return true;
    return false;
  }
  onPointerDown(e) {
    var _a, _b;
    (_b = (_a = e.target).setPointerCapture) == null ? void 0 : _b.call(_a, e.pointerId);
    const isPen = e.pointerType === "pen";
    const isTouch = e.pointerType === "touch";
    if (isPen) {
      this.penActive = true;
      this.penSeen = true;
      this.panStart = null;
      this.pinch = null;
      this.cancelInProgressStroke();
    }
    this.pointers.set(e.pointerId, {
      id: e.pointerId,
      type: e.pointerType,
      clientX: e.clientX,
      clientY: e.clientY
    });
    if (isTouch) {
      const touches = [...this.pointers.values()].filter((p) => p.type === "touch");
      if (this.penActive) {
        return;
      }
      if (touches.length >= 2) {
        this.beginPinch(touches[0], touches[1]);
        this.cancelInProgressStroke();
        return;
      }
      if (this.penSeen || this.tool === "pan") {
        this.beginPan(e);
        return;
      }
    }
    if (e.pointerType === "mouse" && (e.button === 1 || e.button === 2)) {
      this.beginPan(e);
      return;
    }
    if (this.tool === "pan") {
      this.beginPan(e);
      return;
    }
    if (!this.isPenLikeForDrawing(e) && !isTouch)
      return;
    const world = this.screenToWorld(e.clientX, e.clientY);
    if (this.tool === "pencil") {
      this.beginStroke(e, world);
    } else if (this.tool === "eraser") {
      this.pushUndoSnapshot();
      this.eraseAt(world.x, world.y);
    } else if (this.tool === "select") {
      this.beginSelection(e, world);
    }
  }
  onPointerMove(e) {
    const prev = this.pointers.get(e.pointerId);
    if (!prev)
      return;
    prev.clientX = e.clientX;
    prev.clientY = e.clientY;
    if (this.pinch && (e.pointerId === this.pinch.ids[0] || e.pointerId === this.pinch.ids[1])) {
      this.updatePinch();
      return;
    }
    if (this.panStart) {
      const dx = e.clientX - this.panStart.clientX;
      const dy = e.clientY - this.panStart.clientY;
      this.view.x = this.panStart.viewX + dx;
      this.view.y = this.panStart.viewY + dy;
      this.scheduleRender();
      return;
    }
    const world = this.screenToWorld(e.clientX, e.clientY);
    if (prev.stroke) {
      this.extendStroke(prev.stroke, world, e);
      this.scheduleRender();
      return;
    }
    if (this.tool === "eraser" && e.buttons !== 0) {
      this.eraseAt(world.x, world.y);
      return;
    }
    if (this.selectionDrag) {
      this.continueSelectionDrag(e);
      return;
    }
    if (this.selectionBox && e.buttons !== 0) {
      this.selectionBox.x1 = world.x;
      this.selectionBox.y1 = world.y;
      this.scheduleRender();
    }
  }
  onPointerUp(e) {
    const p = this.pointers.get(e.pointerId);
    if (!p)
      return;
    if (p.stroke) {
      this.finishStroke(p.stroke);
    }
    this.pointers.delete(e.pointerId);
    if (e.pointerType === "pen") {
      const anyPen = [...this.pointers.values()].some((pp) => pp.type === "pen");
      if (!anyPen)
        this.penActive = false;
    }
    if (this.pinch) {
      const a = this.pointers.get(this.pinch.ids[0]);
      const b = this.pointers.get(this.pinch.ids[1]);
      if (!a || !b)
        this.pinch = null;
    }
    if (this.panStart && this.pointers.size === 0) {
      this.panStart = null;
    }
    if (this.selectionBox && e.buttons === 0) {
      this.commitSelectionBox();
    }
    if (this.selectionDrag && this.pointers.size === 0) {
      this.selectionDrag = null;
      this.scheduleSave();
    }
  }
  beginPan(e) {
    this.panStart = {
      viewX: this.view.x,
      viewY: this.view.y,
      clientX: e.clientX,
      clientY: e.clientY
    };
  }
  beginPinch(a, b) {
    const dx = a.clientX - b.clientX;
    const dy = a.clientY - b.clientY;
    const dist = Math.hypot(dx, dy);
    const rect = this.container.getBoundingClientRect();
    const midClient = { x: (a.clientX + b.clientX) / 2, y: (a.clientY + b.clientY) / 2 };
    const midScreen = { x: midClient.x - rect.left, y: midClient.y - rect.top };
    const midWorld = {
      x: (midScreen.x - this.view.x) / this.view.scale,
      y: (midScreen.y - this.view.y) / this.view.scale
    };
    this.pinch = {
      ids: [a.id, b.id],
      startDist: Math.max(1, dist),
      startScale: this.view.scale,
      startMidWorld: midWorld
    };
    this.panStart = null;
  }
  updatePinch() {
    if (!this.pinch)
      return;
    const a = this.pointers.get(this.pinch.ids[0]);
    const b = this.pointers.get(this.pinch.ids[1]);
    if (!a || !b)
      return;
    const dx = a.clientX - b.clientX;
    const dy = a.clientY - b.clientY;
    const dist = Math.max(1, Math.hypot(dx, dy));
    const ratio = dist / this.pinch.startDist;
    const newScale = Math.max(MIN_SCALE, Math.min(MAX_SCALE, this.pinch.startScale * ratio));
    const rect = this.container.getBoundingClientRect();
    const midScreen = {
      x: (a.clientX + b.clientX) / 2 - rect.left,
      y: (a.clientY + b.clientY) / 2 - rect.top
    };
    this.view.scale = newScale;
    this.view.x = midScreen.x - this.pinch.startMidWorld.x * newScale;
    this.view.y = midScreen.y - this.pinch.startMidWorld.y * newScale;
    this.scheduleRender();
  }
  onWheel(e) {
    e.preventDefault();
    if (e.ctrlKey || e.metaKey) {
      const factor = Math.exp(-e.deltaY * 2e-3);
      this.zoomAtClient(e.clientX, e.clientY, factor);
    } else {
      this.view.x -= e.deltaX;
      this.view.y -= e.deltaY;
      this.scheduleRender();
    }
  }
  zoomAtClient(clientX, clientY, factor) {
    const rect = this.container.getBoundingClientRect();
    const sx = clientX - rect.left;
    const sy = clientY - rect.top;
    const wx = (sx - this.view.x) / this.view.scale;
    const wy = (sy - this.view.y) / this.view.scale;
    const newScale = Math.max(MIN_SCALE, Math.min(MAX_SCALE, this.view.scale * factor));
    this.view.scale = newScale;
    this.view.x = sx - wx * newScale;
    this.view.y = sy - wy * newScale;
    this.scheduleRender();
  }
  zoomAtCenter(factor) {
    const rect = this.container.getBoundingClientRect();
    this.zoomAtClient(rect.left + rect.width / 2, rect.top + rect.height / 2, factor);
  }
  zoomToFit() {
    if (this.boardData.strokes.length === 0) {
      this.resetView();
      return;
    }
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const s of this.boardData.strokes) {
      const b = strokeBounds(s);
      if (b.minX < minX)
        minX = b.minX;
      if (b.minY < minY)
        minY = b.minY;
      if (b.maxX > maxX)
        maxX = b.maxX;
      if (b.maxY > maxY)
        maxY = b.maxY;
    }
    const w = maxX - minX;
    const h = maxY - minY;
    const rect = this.container.getBoundingClientRect();
    const pad = 40;
    const scale = Math.max(
      MIN_SCALE,
      Math.min(MAX_SCALE, Math.min((rect.width - pad * 2) / Math.max(w, 1), (rect.height - pad * 2) / Math.max(h, 1)))
    );
    this.view.scale = scale;
    this.view.x = rect.width / 2 - (minX + maxX) / 2 * scale;
    this.view.y = rect.height / 2 - (minY + maxY) / 2 * scale;
    this.scheduleRender();
  }
  resetView() {
    this.view = { x: 0, y: 0, scale: 1 };
    this.scheduleRender();
  }
  beginStroke(e, world) {
    this.pushUndoSnapshot();
    const stroke = {
      id: uid(),
      color: this.color,
      size: this.size,
      points: [{ x: world.x, y: world.y, p: this.pressureFor(e) }]
    };
    this.boardData.strokes.push(stroke);
    const p = this.pointers.get(e.pointerId);
    if (p)
      p.stroke = stroke;
    this.scheduleRender();
  }
  extendStroke(stroke, world, e) {
    const last = stroke.points[stroke.points.length - 1];
    const dx = world.x - last.x;
    const dy = world.y - last.y;
    if (dx * dx + dy * dy < 0.25 / (this.view.scale * this.view.scale))
      return;
    stroke.points.push({ x: world.x, y: world.y, p: this.pressureFor(e) });
  }
  finishStroke(stroke) {
    if (stroke.points.length === 0) {
      this.boardData.strokes = this.boardData.strokes.filter((s) => s !== stroke);
    }
    this.scheduleSave();
  }
  cancelInProgressStroke() {
    let changed = false;
    for (const p of this.pointers.values()) {
      if (p.stroke) {
        this.boardData.strokes = this.boardData.strokes.filter((s) => s !== p.stroke);
        p.stroke = void 0;
        changed = true;
      }
    }
    if (changed) {
      if (this.undoStack.length > 0)
        this.undoStack.pop();
      this.scheduleRender();
    }
  }
  pressureFor(e) {
    if (e.pointerType === "pen" && this.plugin.settings.pressureEnabled) {
      return Math.max(0.05, Math.min(1, e.pressure || 0.5));
    }
    return 0.5;
  }
  eraseAt(x, y) {
    const r = this.eraseRadius / this.view.scale;
    const before = this.boardData.strokes.length;
    this.boardData.strokes = this.boardData.strokes.filter((s) => !strokeHit(s, x, y, r));
    if (this.boardData.strokes.length !== before) {
      this.scheduleRender();
      this.scheduleSave();
    }
  }
  beginSelection(e, world) {
    const r = 4 / this.view.scale;
    const hit = this.boardData.strokes.find((s) => strokeHit(s, world.x, world.y, r));
    if (hit && this.selectedIds.has(hit.id)) {
      this.beginSelectionDrag(e);
      return;
    }
    if (hit) {
      this.selectedIds.clear();
      this.selectedIds.add(hit.id);
      this.beginSelectionDrag(e);
      this.scheduleRender();
      return;
    }
    this.selectedIds.clear();
    this.selectionBox = { x0: world.x, y0: world.y, x1: world.x, y1: world.y };
    this.scheduleRender();
  }
  commitSelectionBox() {
    if (!this.selectionBox)
      return;
    const { x0, y0, x1, y1 } = this.selectionBox;
    const box = {
      minX: Math.min(x0, x1),
      minY: Math.min(y0, y1),
      maxX: Math.max(x0, x1),
      maxY: Math.max(y0, y1)
    };
    this.selectedIds.clear();
    if (box.maxX - box.minX > 2 && box.maxY - box.minY > 2) {
      for (const s of this.boardData.strokes) {
        if (rectIntersectsBounds(box, strokeBounds(s)))
          this.selectedIds.add(s.id);
      }
    }
    this.selectionBox = null;
    this.scheduleRender();
  }
  beginSelectionDrag(e) {
    const originalPoints = /* @__PURE__ */ new Map();
    for (const s of this.boardData.strokes) {
      if (this.selectedIds.has(s.id)) {
        originalPoints.set(
          s.id,
          s.points.map((p) => ({ x: p.x, y: p.y, p: p.p }))
        );
      }
    }
    this.pushUndoSnapshot();
    this.selectionDrag = {
      startClientX: e.clientX,
      startClientY: e.clientY,
      lastClientX: e.clientX,
      lastClientY: e.clientY,
      originalPoints
    };
  }
  continueSelectionDrag(e) {
    if (!this.selectionDrag)
      return;
    const dx = (e.clientX - this.selectionDrag.startClientX) / this.view.scale;
    const dy = (e.clientY - this.selectionDrag.startClientY) / this.view.scale;
    for (const s of this.boardData.strokes) {
      const orig = this.selectionDrag.originalPoints.get(s.id);
      if (!orig)
        continue;
      for (let i = 0; i < s.points.length; i++) {
        s.points[i].x = orig[i].x + dx;
        s.points[i].y = orig[i].y + dy;
      }
    }
    this.selectionDrag.lastClientX = e.clientX;
    this.selectionDrag.lastClientY = e.clientY;
    this.scheduleRender();
  }
  deleteSelection() {
    if (this.selectedIds.size === 0)
      return;
    this.pushUndoSnapshot();
    this.boardData.strokes = this.boardData.strokes.filter((s) => !this.selectedIds.has(s.id));
    this.selectedIds.clear();
    this.scheduleRender();
    this.scheduleSave();
  }
  clearAllPrompt() {
    if (this.boardData.strokes.length === 0)
      return;
    new ConfirmModal(this.app, "Clear the entire whiteboard?", () => {
      this.pushUndoSnapshot();
      this.boardData.strokes = [];
      this.selectedIds.clear();
      this.scheduleRender();
      this.scheduleSave();
    }, "Clear").open();
  }
  handleKey(e) {
    if (!this.isActiveLeaf())
      return;
    if (this.isEditableTarget(e.target))
      return;
    const mod = e.metaKey || e.ctrlKey;
    if (mod && !e.shiftKey && e.key.toLowerCase() === "z") {
      e.preventDefault();
      this.undo();
    } else if (mod && (e.key.toLowerCase() === "y" || e.shiftKey && e.key.toLowerCase() === "z")) {
      e.preventDefault();
      this.redo();
    } else if (!mod && (e.key === "Delete" || e.key === "Backspace") && this.selectedIds.size > 0) {
      e.preventDefault();
      this.deleteSelection();
    } else if (!mod && e.key.toLowerCase() === "p") {
      this.tool = "pencil";
      this.refreshToolbarState();
    } else if (!mod && e.key.toLowerCase() === "e") {
      this.tool = "eraser";
      this.refreshToolbarState();
    } else if (!mod && e.key.toLowerCase() === "v") {
      this.tool = "select";
      this.refreshToolbarState();
    } else if (!mod && e.key.toLowerCase() === "h") {
      this.tool = "pan";
      this.refreshToolbarState();
    }
  }
  isActiveLeaf() {
    return this.app.workspace.getActiveViewOfType(PencilWhiteboardView) === this;
  }
  isEditableTarget(target) {
    const el = target;
    if (!el)
      return false;
    const tag = el.tagName;
    if (tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT")
      return true;
    if (el.isContentEditable)
      return true;
    return false;
  }
  pushUndoSnapshot() {
    this.undoStack.push(this.cloneData());
    if (this.undoStack.length > 200)
      this.undoStack.shift();
    this.redoStack = [];
  }
  cloneData() {
    return JSON.parse(JSON.stringify(this.boardData));
  }
  undo() {
    const prev = this.undoStack.pop();
    if (!prev)
      return;
    this.redoStack.push(this.cloneData());
    this.boardData = prev;
    this.selectedIds.clear();
    this.scheduleRender();
    this.scheduleSave();
  }
  redo() {
    const next = this.redoStack.pop();
    if (!next)
      return;
    this.undoStack.push(this.cloneData());
    this.boardData = next;
    this.selectedIds.clear();
    this.scheduleRender();
    this.scheduleSave();
  }
  scheduleSave() {
    this.boardData.view = { ...this.view };
    try {
      this.requestSave();
    } catch (e) {
      console.error("Pencil: failed to save", e);
      new import_obsidian3.Notice("Pencil: failed to save whiteboard");
    }
  }
};

// src/main.ts
var FILE_EXT = "pencil";
var DEFAULT_SETTINGS = {
  customColors: [],
  pressureEnabled: true
};
var PencilPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    registerIcons();
    await this.loadSettings();
    this.registerView(VIEW_TYPE_PENCIL, (leaf) => new PencilWhiteboardView(leaf, this));
    this.registerExtensions([FILE_EXT], VIEW_TYPE_PENCIL);
    this.addRibbonIcon(ICON.pencil, "New whiteboard", async () => {
      await this.createAndOpenWhiteboard();
    });
    this.addCommand({
      id: "create-whiteboard",
      name: "Create new whiteboard",
      callback: async () => {
        await this.createAndOpenWhiteboard();
      }
    });
  }
  onunload() {
  }
  async createAndOpenWhiteboard() {
    const folder = this.getActiveFolder();
    const base = "Whiteboard";
    const path = await this.uniquePath(folder, base);
    try {
      const file = await this.app.vault.create(path, serializeData({ ...EMPTY_DATA }));
      const leaf = this.app.workspace.getLeaf(true);
      await leaf.openFile(file);
    } catch (e) {
      console.error("Pencil: failed to create whiteboard", e);
      new import_obsidian4.Notice("Pencil: failed to create whiteboard");
    }
  }
  getActiveFolder() {
    const active = this.app.workspace.getActiveFile();
    if (active && active.parent)
      return active.parent.path;
    return "";
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded != null ? loaded : {});
    if (!Array.isArray(this.settings.customColors))
      this.settings.customColors = [];
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async uniquePath(folder, base) {
    const prefix = folder ? `${folder}/` : "";
    let candidate = (0, import_obsidian4.normalizePath)(`${prefix}${base}.${FILE_EXT}`);
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(candidate) instanceof import_obsidian4.TFile) {
      candidate = (0, import_obsidian4.normalizePath)(`${prefix}${base} ${i}.${FILE_EXT}`);
      i += 1;
    }
    return candidate;
  }
};

/* nosourcemap */